export const MINUTE_IN_MILISECONDS = 60000;
export const THREE_MINUTES_IN_MILISECONDS = MINUTE_IN_MILISECONDS * 3;
export const TEN_MINUTES_IN_MILISECONDS = MINUTE_IN_MILISECONDS * 10;
export const THIRTY_MINUTES_IN_MILISECONDS = MINUTE_IN_MILISECONDS * 30;
export const HOUR_IN_MILISECONDS = MINUTE_IN_MILISECONDS * 60;
export const DAY_IN_MILISECONDS = HOUR_IN_MILISECONDS * 24;
